org: sebastianchu
service: api-productos

provider:
  name: aws
  runtime: nodejs20.x
  timeout: 30
  region: us-east-1
  iam:
    role: arn:aws:iam::971808350791:role/LabRole
  environment:
    TABLE_NAME: ProductosTable-dev
    JWT_SECRET: ${env:JWT_SECRET}

functions:
  crearProducto:
    handler: handler.crearProducto
    events:
      - http:
          path: /productos
          method: post
          cors: true
          integration: lambda

  listarProductos:
    handler: handler.listarProductos
    events:
      - http:
          path: /productos
          method: get
          cors: true
          integration: lambda

  buscarProducto:
    handler: handler.buscarProducto
    events:
      - http:
          path: /productos/{codigo}
          method: get
          cors: true
          integration: lambda

  modificarProducto:
    handler: handler.modificarProducto
    events:
      - http:
          path: /productos/{codigo}
          method: put
          cors: true
          integration: lambda

  eliminarProducto:
    handler: handler.eliminarProducto
    events:
      - http:
          path: /productos/{codigo}
          method: delete
          cors: true
          integration: lambda

resources:
  Resources:
    ProductosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ProductosTable-dev
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: codigo
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: codigo
            KeyType: RANGE

